name: CI
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'input app name'
        required: false
        type: string

env:
    config: |
        {
            "clouds1": {
                "aws": "ec2",
                "azure": "functions"
            },
            "clouds2": {
                "aws": "ec2",
                "azure": "functions"
            }
        }
jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
        - name: matrix
          id: matrix
          run: |
            json=$(echo '${{env.config}}' | jq -r .clouds1)
            echo "aws=$(echo $json | jq -r .aws)" >> $GITHUB_OUTPUT
    outputs:
      aws: ${{steps.matrix.outputs.aws}}

  build:
    runs-on: ubuntu-latest
    if: ${{needs.set-matrix.outputs.aws == 'ec2'}}
    needs: [set-matrix]
    steps:
      # - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Clone repo
        run: |
            echo ${{needs.set-matrix.outputs.aws}} output data
            git clone https://github.com/niyas-ali/sample-dotnetcore-library.git
            cd sample-dotnetcore-library
            git pull origin dev
            git checkout dev
            git status

      # - name: Build
      #   working-directory: sample-dotnetcore-library
      #   run: |
      #     dotnet restore 
      #     dotnet build -c Release --no-restore
      #     dotnet pack -c Release -o ./nuget
      #     ls -p ./nuget
      #     dotnet nuget push --source https://nuget.pkg.github.com/${{github.actor}} ./nuget/*
